#!/bin/bash


###################################
# SCRIPT D'INSTALATION ARCH LINUX #
###################################


# VARIABLE DE CONFIGURATION DE L'INSTALATION

# langue
LANGUE_CLAVIER=fr-latin 	# liste langue clavier : ls /usr/share/kbd/keymaps/**/*.map.gz
POLICE=default8x16 			# liste police dispo : ls /usr/share/kbd/consolefonts/
TIMEZONE=Europe/Paris 		# liste timezone : timedatectl list-timezones

# cryptage disque
ENCRYPTED=1					# crypte le disque (0=false;1=true)
PASSPHRASE=hamoud			# mdp pour decrypté la partition crypté
DISKNAME=sda				# nom du disque par defaut sda sinon lsblk
SIZEBOOTPART=1				# taille boot partition conseiller 1G min
SIZEHOMEPART=				# `` home ``, si !defini : reste taille disque <!> G at end
OVERWRITEDISK=0				# ecrit random data sur part home (tres long) (0=false;1=true)

# SCRIPT

# change la langue du claver
loadkeys $LANGUE_CLAVIER

# change police 
setfont $POLICE

# met a jour l'heure et date a la timezone
timedatectl set-timezone $TIMEZONE
# synchronise hardware (mdr jsp ce que sa fait mais c'est bien de le faire askip)
hwclock --systohc

# partitione disque differament si crypter activé ou pas
if [ $ENCRYPTED -eq 1 ]; then

	echo "q" | fdisk /dev/$DISKNAME

	# partionne le disque en deux (boot et home)
	echo ","$SIZEBOOTPART"G" | sfdisk /dev/$DISKNAME 1	# part pour boot (sda1)
	echo ","$SIZEHOMEPART | sfdisk /dev/$DISKNAME 2		# part pour home (sda2)
	
	# formatte la partition pour le boot dans le format fat 
	mkfs.fat -F32 /dev/$DISKNAME"1"

	# TEMP
	# remplit le disque de donné random pour rendre ilisible les meta-donné
	if [ $OVERWRITEDISK -eq 1 ]; then
		dd if=/dev/urandom of=/dev/$DISKNAME"2"
	fi

	# active l'encryption (jsp si c'est un vrai mot) la partition sda2
	#echo $passphrase | cryptsetup luksformat /dev/sda2 -
	
else

fi
