#!/bin/bash


load=$1
cd ~/.minecraft/mods

for modpack in `ls --ignore=*.jar`; do
	if [ $(ls $modpack | wc -l) -eq 0 ]; then
		mv *.jar $modpack
	fi
done

if [[ $load != "" ]]; then
	mv $load/*.jar . 
fi
