#!/bin/bash

act=$(echo -e "shutdown\nreboot\nlock" | dmenu -p "action:")

case $act in
    "shutdown")
        shutdown 0
        ;;
    "reboot")
        reboot
        ;;
    "lock")
        lockscreen
        ;;
esac
