#!/bin/bash
# compile un programme en c++ en mode release

if [[ $1 != "" ]]; then
	cd $1
fi

project=$(grep "^\(project(\)" CMakeLists.txt) || exit
project=${project#project(}
project=${project%% *}
cd $(pwd)/build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-03 ..
#cmake -DCMAKE_BUILD_TYPE=Release ..
#cmake -CMAKE_CXX_FLAGS=-03 ..
make

figlet "noice" | lolcat

echo -n "lunch $project ? (y/n) "
read input
if [[ input = "y" ]]; then
	./$project
fi
